services:
  - mongodb
  - docker

language: go
go:
- "1.10"

before_install:
  - make sanitize
  - make test

script:
  - make docker
  - docker-compose up -d

deploy:
  - provider: script
    script: make docker_upload
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^develop|master$

notifications:
  email:
    - ops@safetychanger.com

  slack: safetychanger:iBdUKrm6abL7BQNtoIpihFA3
