services: mongodb
language: go
go:
- "1.10"

before_install:
  - make sanitize
  - make test

script:
  - make build_linux

deploy:
  - provider: script
    script: make docker_upload
    on:
      branch: master

notifications:
  email:
    - ops@safetychanger.com

  slack: safetychanger:iBdUKrm6abL7BQNtoIpihFA3
